/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei/native';
import { PanResponder, View } from 'react-native';

export default function Model(props) {
  const { nodes, materials } = useGLTF(require('../assets/Model.glb'));
  const groupRef = useRef();
  const [rotation, setRotation] = useState(0);

  const panResponder = useRef(
    PanResponder.create({
      onStartShouldSetPanResponder: () => true,
      onMoveShouldSetPanResponder: () => true,
      onPanResponderMove: (evt, { dy }) => {
        const newRotation = rotation + dy * 0.01;
        setRotation(newRotation);
        if (groupRef.current) {
          groupRef.current.rotation.x = newRotation;
        }
      },
    })
  ).current;

  return (
    <group {...props} dispose={null} scale={0.15} position={[0, 2.5, 0]}>
      <group ref={groupRef} position={[-15, 0, -5]} scale={0.002}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm1.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm10.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm100.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm101.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm102.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm103.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm104.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm105.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm106.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm107.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm108.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm109.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm11.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm110.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm111.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm112.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm113.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm114.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm115.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm116.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm117.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm118.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm119.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm12.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm13.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm14.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm15.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm16.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm17.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm18.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm19.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm2.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm20.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm21.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm22.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm23.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm24.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm25.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm26.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm27.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm28.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm29.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm3.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm30.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm31.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm32.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm33.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm34.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm35.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm36.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm37.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm38.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm39.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm4.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm40.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm41.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm42.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm43.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm44.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm45.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm46.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm47.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm48.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm49.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm5.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm50.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm51.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm52.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm53.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm54.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm55.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm56.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm57.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm58.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm59.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm6.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm60.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm61.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm62.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm63.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm64.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm65.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm66.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm67.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm68.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm69.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm7.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm70.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm71.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm72.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm73.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm74.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm75.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm76.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm77.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm78.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm79.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm8.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm80.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm81.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm82.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm83.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm84.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm85.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm86.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm87.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm88.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm89.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm9.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm90.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm91.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm92.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm93.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm94.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm95.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm96.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm97.geometry}
          material={materials.Sash}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm98.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1220_x_1220mm99.geometry}
          material={materials.Trim}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1700_x_2000mm.geometry}
          material={materials['Paint_-_Sienna']}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1700_x_2000mm1.geometry}
          material={materials['Paint_-_Sienna']}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1700_x_2000mm2.geometry}
          material={materials['Wood_-_Birch_-_Solid_Stained_Light_Low_Gloss']}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_1700_x_2000mm3.geometry}
          material={materials['Wood_-_Birch_-_Solid_Stained_Light_Low_Gloss']}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_300mm_Generic.geometry}
          material={materials.Default}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square1.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square10.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square11.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square12.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square13.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square14.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square15.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square16.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square17.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square18.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square19.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square2.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square20.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square21.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square22.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square23.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square24.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square25.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square26.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square27.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square28.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square29.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square3.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square30.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square31.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square32.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square33.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square34.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square35.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square36.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square37.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square38.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square39.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square4.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square40.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square41.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square42.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square43.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square44.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square45.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square46.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square47.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square48.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square49.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square5.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square50.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square51.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square52.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square53.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square54.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square55.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square56.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square57.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square58.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square59.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square6.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square60.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square61.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square62.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square63.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square64.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square65.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square66.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square67.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square68.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square69.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square7.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square70.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square71.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square72.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square73.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square74.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square75.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square76.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square77.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square78.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square79.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square8.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square80.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square81.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square82.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square83.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square84.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square85.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square86.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square87.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square88.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square89.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square9.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square90.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square91.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square92.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_30mm_Square93.geometry}
          material={materials.Aluminium}
          position={[0.001, 0, 0]}
        />
        <group position={[0.001, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_24.geometry}
            material={materials.Default}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_24_1.geometry}
            material={materials.Ceiling_Tile_600_x_1200}
          />
        </group>
        <group position={[0.001, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_25.geometry}
            material={materials.Default}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_25_1.geometry}
            material={materials.Ceiling_Tile_600_x_600}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_850_x_2000mm.geometry}
          material={materials['Wood_-_Birch_-_Solid_Stained_Light_Low_Gloss']}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_850_x_2000mm1.geometry}
          material={materials['Paint_-_Sienna']}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_850_x_2000mm2.geometry}
          material={materials['Paint_-_Sienna']}
          position={[0.001, 0, 0]}
        />
        <group position={[0.001, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_10.geometry}
            material={materials['Concrete_Masonry,_Floor_Block']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_10_1.geometry}
            material={materials['Concrete,_Sand/Cement_Screed']}
          />
        </group>
        <group position={[0.001, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_8.geometry}
            material={materials['Concrete_Masonry,_Floor_Block']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_8_1.geometry}
            material={materials.Floor_Tile}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed1.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed10.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed11.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed12.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed13.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed14.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed15.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed16.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed17.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed18.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed19.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed2.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed20.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed21.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed22.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed23.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed24.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed25.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed26.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed27.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed28.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed29.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed3.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed30.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed31.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed32.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed33.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed34.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed35.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed36.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed37.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed38.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed39.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed4.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed40.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed41.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed42.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed43.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed44.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed45.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed46.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed47.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed48.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed49.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed5.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed50.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed51.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed6.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed7.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed8.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Glazed9.geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['g_M_Door-Curtain-Wall-Double-Glass'].geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['g_M_Door-Curtain-Wall-Double-Glass1'].geometry}
          material={materials.Glass}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['g_M_Door-Curtain-Wall-Double-Glass2'].geometry}
          material={materials.Aluminum}
          position={[0.001, 0, 0]}
        />
        <group position={[0.001, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_23.geometry}
            material={materials.Metal_Stud_Layer}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_23_1.geometry}
            material={materials.Gypsum_Wall_Board}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['g_Roof_Generic-125mm'].geometry}
          material={materials['Roofing,_Tile']}
          position={[8439.065, 6854.473, 5251.069]}
        />
        <group position={[0.001, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_9.geometry}
            material={materials['Concrete_Masonry,_Floor_Block']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_9_1.geometry}
            material={materials['Floor_Tile(300mm_x_300mm)']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Standard.geometry}
          material={materials.Default}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.g_Standard1.geometry}
          material={materials.Default}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['g_Wall-Ext_215Bwk'].geometry}
          material={materials['Brick,_Common']}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['g_Wall-Ext_215Bwk1'].geometry}
          material={materials['Brick,_Common']}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['g_Wall-Ext_215Bwk2'].geometry}
          material={materials['Brick,_Common']}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['g_Wall-Ext_215Bwk3'].geometry}
          material={materials['Brick,_Common']}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['g_Wall-Ext_215Bwk4'].geometry}
          material={materials['Brick,_Common']}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['g_Wall-Ext_215Bwk5'].geometry}
          material={materials['Brick,_Common']}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['g_Wall-Ext_215Bwk6'].geometry}
          material={materials['Brick,_Common']}
          position={[0.001, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['g_Wall-Ext_215Bwk7'].geometry}
          material={materials['Brick,_Common']}
          position={[0.001, 0, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload(require('../assets/Model.glb'));
